-- Adición de nuevos tipos de maestros.
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 20, 'Intensidad horaria' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 21 , 'Pruebas minimas' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 22 , 'Evaluación Aprendizaje' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 23 , 'Mayoría de edad' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 24 , 'Semestre' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 25 , 'Tipo parametrizacion' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 26 , 'Semanas lectivas' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 27 , 'Duracion momentos' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 28 , 'Momentos docente' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 29 , 'Estados estudios académicos' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 30 , 'Estado' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 31 , 'Promedio promoción' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 32 , 'Calificación máxima' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 33 , 'Calificación mínima' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 34, 'Parametrización institucional momentos docente', 0 )