s-- Precarga maestro Grados
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Transición', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Pre-Jardín', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Jardín', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Primero', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Segundo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Tercero', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Cuarto', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Quinto', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Sexto', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Séptimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Octavo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Noveno', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Décimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Undécimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Duodécimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Trigésimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Cuadragésimo', 5, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-1', 5, 1, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-2', 5, 1, 1, 2 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-3', 5, 1, 1, 3 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-4', 5, 1, 1, 4 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-5', 5, 1, 1, 5 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI-6', 5, 1, 1, 6 )

-- Precarga maestro Nivel
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Preescolar', 6, 1, 1, 22 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Primaria', 6, 1, 1, 23 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Secundaria', 6, 1, 1, 24 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Media académica', 6, 1, 1, 25 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Media técnica', 6, 1, 1, 26 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'CLEI', 6, 1, 1, 7 )

-- Precarga maestro Horario
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Mañana', 12, 1, 1, 9 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Tarde', 12, 1, 1, 10 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Nocturna', 12, 1, 1, 11 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Sabatina', 12, 1, 1, 12 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Dominical', 12, 1, 1, 13 )

-- Precarga maestro Jornada académica
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Única', 13, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Compartida', 13, 1, 1 )

-- Precarga maestro Clasificación
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Primaria', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Secundaria', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Bachiller', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Técnica', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Tecnológica', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Universitario', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Especialización', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Magister', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Doctorado', 14, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'PHD', 14, 1, 1 )

-- Precarga maestro Grado en el escalafón
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'A', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'B', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '1°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '2°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '3°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '4°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '5°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '6°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '7°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '8°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '9°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '10°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '11°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '12°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '13°', 15, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( '14°', 15, 1, 1 )

-- Precarga maestro Rol institucional
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado ) VALUES ( 'Estudiante', 16, 1, 1 )
INSERT INTO dbo.Maestros ( Descripcion, IdTipoMaestro, IdSede, Estado, Consecutivo ) VALUES ( 'Docente', 16, 1, 1, 31 )