INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 1 , 'Desempeños evaluativos' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 2 , 'Aspectos evaluativos' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 3 , 'Entidades prestadoras de salud' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 4 , 'Tipos de documentos para soporte por roles' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 5 , 'Grados' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 6 , 'Nivel' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 7 , 'Área' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 8 , 'Tipos de aula' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 9 , 'Tipos de identificaciones' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 10 , 'Cargos' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 11 , 'Grupos sanguíneos' , 0 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 12 , 'Horario' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 13 , 'Jornada académica' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 14 , 'Clasificación' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 15 , 'Grado en el escalafón' , 1 )
INSERT INTO dbo.TipoMaestros ( Id, Descripcion, Administrable ) VALUES ( 16 , 'Rol institucional' , 0 )
